apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: route-example
  namespace: kong-podinfo
spec:
  sources:
    - match:
        kuma.io/service: kong-proxy_kong_svc_80
  destinations:
    - match:
        kuma.io/service: podinfo-service_kong-podinfo_svc_9898
  conf:
    split:
      - weight: 100
        destination:
          kuma.io/service: podinfo-service_kong-podinfo_svc_9898
          version: 'v1'
