apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: route-example
spec:
  sources:
    - match:
        kuma.io/service: podinfo_kong-podinfo_svc_9898
  destinations:
    - match:
        kuma.io/service: podinfo_kong-podinfo_svc_9898
  conf:
    split:
      - weight: 0
        destination:
          kuma.io/service: podinfo_kong-podinfo_svc_9898
          version: 'v0'
      - weight: 50
        destination:
          kuma.io/service: podinfo_kong-podinfo_svc_9898
          version: 'v1'

